### ISSUE TITLE
swaygrab crashes when tryign to make a screenshot

### ISSUE THREAD

**Issue by zetok** [SirCmpwn/sway#449]
Hardened Gentoo x86_64

sway: 25973212367848e25c538301985ad2b1fd03ea02
newest (currently) wlc

Reproducible: Always

If more info / gdb output is needed, please say so.

```
$ swaygrab working/sway/ff-start-problem.png
*** Error in `swaygrab': munmap_chunk(): invalid pointer: 0x00007ffc84da7096 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7697f)[0x7f0d8bc4a97f]
/lib64/libc.so.6(+0x7c58e)[0x7f0d8bc5058e]
swaygrab(main+0x2f2)[0x556b7c1fab67]
/lib64/libc.so.6(__libc_start_main+0x114)[0x7f0d8bbf49e4]
swaygrab(_start+0x29)[0x556b7c1f9f29]
======= Memory map: ========
556b7c1f8000-556b7c1fd000 r-xp 00000000 fc:00 1181965                    /usr/bin/swaygrab
556b7c3fc000-556b7c3fd000 r--p 00004000 fc:00 1181965                    /usr/bin/swaygrab
556b7c3fd000-556b7c3fe000 rw-p 00005000 fc:00 1181965                    /usr/bin/swaygrab
556b7c9aa000-556b7c9cb000 rw-p 00000000 00:00 0                          [heap]
7f0d8b79c000-7f0d8b7b2000 r-xp 00000000 fc:00 14694120                   /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.3/libgcc_s.so.1
7f0d8b7b2000-7f0d8b9b1000 ---p 00016000 fc:00 14694120                   /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.3/libgcc_s.so.1
7f0d8b9b1000-7f0d8b9b2000 r--p 00015000 fc:00 14694120                   /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.3/libgcc_s.so.1
7f0d8b9b2000-7f0d8b9b3000 rw-p 00016000 fc:00 14694120                   /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.3/libgcc_s.so.1
7f0d8b9b4000-7f0d8b9cb000 r-xp 00000000 fc:00 8519981                    /lib64/libpthread-2.21.so
7f0d8b9cb000-7f0d8bbcb000 ---p 00017000 fc:00 8519981                    /lib64/libpthread-2.21.so
7f0d8bbcb000-7f0d8bbcc000 r--p 00017000 fc:00 8519981                    /lib64/libpthread-2.21.so
7f0d8bbcc000-7f0d8bbcd000 rw-p 00018000 fc:00 8519981                    /lib64/libpthread-2.21.so
7f0d8bbcd000-7f0d8bbd1000 rw-p 00000000 00:00 0 
7f0d8bbd4000-7f0d8bd71000 r-xp 00000000 fc:00 8519995                    /lib64/libc-2.21.so
7f0d8bd71000-7f0d8bf70000 ---p 0019d000 fc:00 8519995                    /lib64/libc-2.21.so
7f0d8bf70000-7f0d8bf74000 r--p 0019c000 fc:00 8519995                    /lib64/libc-2.21.so
7f0d8bf74000-7f0d8bf76000 rw-p 001a0000 fc:00 8519995                    /lib64/libc-2.21.so
7f0d8bf76000-7f0d8bf7b000 rw-p 00000000 00:00 0 
7f0d8bf7c000-7f0d8bf83000 r-xp 00000000 fc:00 8519976                    /lib64/librt-2.21.so
7f0d8bf83000-7f0d8c182000 ---p 00007000 fc:00 8519976                    /lib64/librt-2.21.so
7f0d8c182000-7f0d8c183000 r--p 00006000 fc:00 8519976                    /lib64/librt-2.21.so
7f0d8c183000-7f0d8c184000 rw-p 00007000 fc:00 8519976                    /lib64/librt-2.21.so
7f0d8c184000-7f0d8c18e000 r-xp 00000000 fc:00 13000485                   /usr/lib64/libjson-c.so.2.0.1
7f0d8c18e000-7f0d8c38e000 ---p 0000a000 fc:00 13000485                   /usr/lib64/libjson-c.so.2.0.1
7f0d8c38e000-7f0d8c38f000 r--p 0000a000 fc:00 13000485                   /usr/lib64/libjson-c.so.2.0.1
7f0d8c38f000-7f0d8c390000 rw-p 0000b000 fc:00 13000485                   /usr/lib64/libjson-c.so.2.0.1
7f0d8c394000-7f0d8c3b7000 r-xp 00000000 fc:00 8519990                    /lib64/ld-2.21.so
7f0d8c5b3000-7f0d8c5b6000 rw-p 00000000 00:00 0 
7f0d8c5b6000-7f0d8c5b7000 r--p 00022000 fc:00 8519990                    /lib64/ld-2.21.so
7f0d8c5b7000-7f0d8c5b8000 rw-p 00023000 fc:00 8519990                    /lib64/ld-2.21.so
7f0d8c5b8000-7f0d8c5ba000 rw-p 00000000 00:00 0 
7f0d8c5ba000-7f0d8c5bc000 rw-p 00000000 00:00 0 
7ffc84d87000-7ffc84da8000 rw-p 00000000 00:00 0                          [stack]
7ffc84dd4000-7ffc84dd6000 r--p 00000000 00:00 0                          [vvar]
7ffc84dd6000-7ffc84dd8000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Error: Signal 6. Printing backtrace
Backtrace: swaygrab(error_handler+0xfa) [0x556b7c1fb9e3]
Backtrace: /lib64/libc.so.6(+0x34380) [0x7f0d8bc08380]
Backtrace: /lib64/libc.so.6(gsignal+0x3b) [0x7f0d8bc082fb]
Backtrace: /lib64/libc.so.6(abort+0x180) [0x7f0d8bc097d0]
Backtrace: /lib64/libc.so.6(+0x76984) [0x7f0d8bc4a984]
Backtrace: /lib64/libc.so.6(+0x7c58e) [0x7f0d8bc5058e]
Backtrace: swaygrab(main+0x2f2) [0x556b7c1fab67]
Backtrace: /lib64/libc.so.6(__libc_start_main+0x114) [0x7f0d8bbf49e4]
Backtrace: swaygrab(_start+0x29) [0x556b7c1f9f29]
```

**Comment by SirCmpwn** [comment]
Please run addr2line on the backtrace to produce file names and line numbers.

**Comment by zetok** [comment]
```
0x00007ffff76532fb in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
55	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff76532fb in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff76547d0 in __GI_abort () at abort.c:89
#2  0x00007ffff7695984 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff7792960 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff769b58e in malloc_printerr (action=3, str=0x7ffff7792988 "munmap_chunk(): invalid pointer", ptr=<optimized out>) at malloc.c:4960
#4  0x0000555555556b67 in main (argc=2, argv=0x7fffffffdcf8) at /var/tmp/portage/wayland-wm/sway-9999/work/sway-9999/swaygrab/main.c:257
```
this?

**Comment by SirCmpwn** [comment]
That looks like a different backtrace? Compare the swaygrab addresses with the original backtrace.

**Comment by zetok** [comment]
>That looks like a different backtrace?

Yeah, since it's reproducible I just ran it again under gdb.

**Comment by SirCmpwn** [comment]
Well this one also has a different error. This error is in the cleanup code. Line 257 frees the path to the file you wanted to save the screenshot to. In this case, the screenshot file should have actually been written by this point in the code. Does it exist?
